### PR TITLE
Multiple Fixes

### PR DESCRIPTION
**Pull request by callmekatootie**
Contains the following:

- unit tests
- integration tests
- Integration of AV Scanner
- Fixing a bug where we used filenames instead of submission ids when uploading files. File names are not unique, submission ids are.
- Dockerization

DO NOT MERGE YET. Still in Review.

### CODE REVIEW

**Comment by callmekatootie** [comment]
Waiting on response to https://github.com/topcoder-platform/submissions-api/issues/28

**Comment by cwdcwd** [comment]
if the decision on zip files only is holding this one up, let's accept zip-only for now and then log a ticket to address alter

**Comment by callmekatootie** [comment]
There's the other related bit where if a submission is created, and instead of the file, a url is passed, during creation, the processor fails.

This is because submission api does not pass the file type in this scenario. Processor uses the file type when uploading to S3 to let S3 know the file type, which comes in handy when downloading the file.

If that is ok for now, we can proceed to merge the PR

**Comment by BadalZ** [comment]
We have fileType added to submission API. topcoder-platform/submissions-api#28 is fixed and so this PR is ready to be merged.

**Pull request merged**
